dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8-dev"
  - "nightly"
install:
  - python setup.py install
  - pip install nose
script: nosetests --logging-level=DEBUG tests
deploy:
  provider: pypi
  user: jamie
  password:
    secure: "VGjC6canDrMeEPALZe5CPmjcs5Iozbmq46G2KqWvCjzyUQBbkPXwv9LTQ6XkefJOzDuMDWzwkEXRfNz2hUX8EjfZxg0D2xek7AB7XTgAsvrMf1Fn61NTBLC8RZakjwB90zFFoKYPiYxlwcmlkPJsZIc46znXhkPkouJ8xbLNkyvKXHd92aT0AoIU2z6Q235a1r4Z/nmyOYn4ZxoWW+c+F10fTXSbExgxLJNo2G+WDBCyTFqGVfUiWzQLPvvByzvjsacFlYFeAS20rKl4S41r6kPamsIeJInI2X7j3JfamLsyZf2UIUl03NVJsB2CCW/n7teNe2blZOWM/RS1gqQbW6NXhV+D9QpneMwwhBSpePuPVNOVZBoC9l/Fch/nxOV4e4DR0MuuVP5CRKEWWF8jmpHZapSB+M5DwUH9bgBrsjJ3MEBfiXAtt9FhHb9Kl6EI6gYgdS7LTnsUHKALQugSIsQf2rGnq+MNVXR0nLyZnmCWhNOBKPCkbytmQJ5vUtdZPDDKahjWbfF0fYjoQ3vAVRM7d+lSoH327xtYQgGWnr8ZaVvrilQamF60mewvBGJSFHKGqXzrjYbmL/I/TWTXYpJYdtzWu9CcYUwr1TugC+BxKAsKCcbmy86xK3N8jd9ufWEPJII030tO0J9dcEUlZItOhssf2GwQcUM9Zf9ifaU="
